# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-07 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Collected'),
        ),
        migrations.AddField(
            model_name='story',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Collected'),
        ),
    ]
