# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment',
            name='sentiment',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
